spring:
  profiles:
    active: qa
---
spring:
  profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/sbdbmysql
    password: ''
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: Welcome to my SpringBoot App!!

---
spring:
  profile: qa
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/sbdbmysql-qa
    password: ''
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: Welcome to my SpringBoot App!!

---

spring:
  profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/sbdbmysql-prod
    password: ''
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: Welcome to my SpringBoot App!!
